# Generated by Django 4.2.7 on 2023-11-20 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="post",
            new_name="post_id",
        ),
    ]
